#!/usr/bin/env python
"""
THIS IS THE IS-ICE COMMUNICATION AND CONTROL SOFTWARE ON THE RASPBERRY PI 3

SENDS COMMANDS TO THE ARDUINO AND RECEIVES SENSOR DATA FOR DISPLAY AND LOGGING
"""

import tkinter as tk
import serial
import time

